import { getTranslation, LANG } from '@shared';
import { TranslationJson } from './Trans';

const json: TranslationJson = {
	app: {
		unableToLoadEvents: 'Unable to load events',
		loading: 'Loading',
		loadingEvents: 'Loading events...',
		eventsExplorerTitle: 'Events Explorer',
		editorMode: 'Editor mode',
		formatLabel: 'Format',
		languageLabel: 'Language',
		languageAuto: 'Follow VS Code',
		eventsLabel: 'events',
		syncLanguage: {
			title: 'Sync Language Setting',
			message: 'Do you want to sync this language setting to VS Code settings?',
			dontAskAgain: 'Don\'t ask me again',
		},
		help: 'Help',
		editorSettings: 'Editor Settings',
		openVSCodeSettings: 'Open VS Code Settings',
		openOnlineEditor: 'Open Online Editor',
		oldEditor: 'Old Editor',
		originalEditor: 'Original Editor',
		basicTutorial: 'Basic Tutorial',
		tutorialSection: 'Tutorial Section',
		discussionSection: 'Discussion Section',
		sampleDownload: 'Sample Download',
		mute: 'Mute',
		unmute: 'Unmute',
	},
	common: {
		info: 'Info',
		yes: 'Yes',
		no: 'No',
		confirm: 'Confirm',
		cancel: 'Cancel',
		back: 'Back',
		close: 'Close',
		save: 'Save',
		add: 'Add',
		edit: 'Edit',
		remove: 'Remove',
		apply: 'Apply',
		openHelper: 'Edit Helper',
		other: 'Other',
		details: 'Details',
		undo: 'Undo',
		redo: 'Redo',
		duplicate: 'Duplicate',
		copy: 'Copy',
		cut: 'Cut',
		moreActions: 'More actions',
	},
	editor: {
		visualEditor: 'Visual Editor',
		jsonEditor: 'JSON Editor',
		editAsJson: 'Edit as JSON',
		backToVisual: 'Back to Visual',
	},
	settings: {
		baseSettingsTitle: 'Base Settings',
		otherSettingsTitle: 'Other Settings',
		configsTitle: 'Configs',
		configSection: 'Configs',
		viewConfigs: 'View configs',
		stage: 'Stage',
		preload: 'Preload',
		resources: 'Resources',
		sources: 'Sources',
		configs: 'Configs',
		stageSize: 'Stage Size',
		background: 'Background',
		resolution: 'Resolution',
		alignment: 'Alignment',
		position: 'Position',
		width: 'Width',
		height: 'Height',
		color: 'Color',
		resourcesExcludePlaceholder: 'Comma separated',
		sourcesPlaceholder: 'Comma separated',
		resolutionModes: {
			showAll: 'Show All',
			exactFit: 'Exact Fit',
			noBorder: 'No Border',
			fixedWidth: 'Fixed Width',
			fixedHeight: 'Fixed Height',
			origin: 'Origin',
		},
		align: {
			left: 'Left',
			center: 'Center',
			right: 'Right',
			top: 'Top',
			middle: 'Middle',
			bottom: 'Bottom',
		},
	},
	events: {
		eventActions: 'Event actions',
		addEvent: 'Add Event',
		folder: 'Folder',
		allFolders: 'All folders',
		noFolder: 'No folder',
		noDescription: 'No description',
		editEvent: 'Edit Event',
		expandEvent: 'Expand Event',
		collapseEvent: 'Collapse Event',
		eventName: 'Event name',
		eventNameExists: 'Event name already exists',
		eventNameRequired: 'Event name is required',
		eventNameInvalid: 'Event name must be 1-60 characters and cannot contain .,/\\*<>{} or whitespace.',
		renameEventNameHint: 'Double click to rename event',
		renameFolderHint: 'Double click to rename folder',
		folderNameInvalid: 'Folder name cannot contain < > { } characters.',
		status: {
			active: 'Active',
			disabled: 'Disabled',
		},
		schedule: {
			start: 'Start',
			checkInterval: 'Check Interval',
			repeats: 'Repeats',
			repeatInterval: 'Repeat Interval',
		},
		flags: {
			devOnly: 'Dev Only',
			referenceOnly: 'Reference Only',
		},
		chips: {
			start: 'Start',
			check: 'Check',
			repeat: 'Repeat',
			interval: 'Interval',
			dev: 'Dev',
			triple: 'Trig/Chk/Act',
		},
		sorting: {
			title: 'Sort',
			editPreset: 'Edit Preset',
			enableSort: 'Enable Sort',
			disableSort: 'Disable Sort',
			savePreset: 'Save Preset',
			loadPreset: 'Load Preset',
			defaultPreset: 'Default Sort',
			presetName: 'Preset Name',
			presetNamePlaceholder: 'Enter preset name',
			existingPresets: 'Existing Presets',
			noPresets: 'No saved presets',
			confirmOverwrite: 'Preset "{{name}}" already exists. Overwrite?',
			selectPreset: 'Select Preset',
			deletePreset: 'Delete Preset',
			confirmDelete: 'Are you sure you want to delete preset "{{name}}"?',
		},
	},
	logic: {
		actionsLabel: 'Logic actions',
		blocks: {
			trigger: 'Triggers',
			check: 'Checks',
			action: 'Actions',
		},
		empty: {
			trigger: 'No triggers',
			check: 'No checks',
			action: 'No actions',
		},
		add: {
			trigger: 'Add Trigger',
			check: 'Add Check',
			action: 'Add Action',
		},
		elseTrigger: 'ELSE',
		unknownType: 'Unknown type',
		addAboveType: 'Add {type} above',
		addBelowType: 'Add {type} below',
		toggleSectionBlock: 'Collapse/Expand {type} section',
		toggleAllType: 'Collapse/Expand all {type}',
		expandTypeList: 'Expand list',
		collapseTypeList: 'Collapse list',
	},
	list: {
		arrayItemActions: 'Array item actions',
		collapse: 'Collapse',
		collapseAll: 'Collapse All',
		expand: 'Expand',
		expandAll: 'Expand All',
		selectAll: 'Select All',
		cancelSelectAll: 'Cancel Select All',
		selectAllList: 'Select all list',
		addItem: 'Add item',
		move: 'Move',
		moveUp: 'Move Up',
		moveDown: 'Move Down',
		moveLeft: 'Move left',
		moveRight: 'Move right',
		moveToTop: 'Move to top',
		moveToBottom: 'Move to bottom',
		moveToEvent: 'Move to event',
		moveSelectionHere: 'Move selection here',
		copyList: 'Copy list',
		cutList: 'Cut list',
		pasteHere: 'Paste',
		pastePrompt: 'Paste logic JSON',
		removeList: 'Remove list',
		removeAll: 'Remove all',
	},
	state: {
		enable: 'Enable',
		disable: 'Disable',
		enableDisable: 'Enable / Disable',
		enableList: 'Enable list',
		disableList: 'Disable list',
		enableDisableList: 'Enable / Disable list',
		booleanTrue: 'True',
		booleanFalse: 'False',
	},
	validation: {
		invalidJson: 'Invalid JSON',
		numberFormatError: 'Value must be type number.',
		noItems: 'No items',
		noMatches: 'No matches',
		missingDefinition: 'Missing definition',
		noSchemaProperties: 'No schema properties defined for this config.',
	},
	navigation: {
		root: 'Root',
		search: 'Search',
		searchResults: 'Search Results',
		goBackTo: 'Back to {{name}}',
		goForwardTo: 'Forward to {{name}}',
		goUpTo: 'Up to {{name}}',
	},
};

getTranslation(LANG.EN).importJson(json);
