import { generateTranslation, ILanguageJson } from '@shared';
import './en';
import './zh';

const json = {
	app: {
		unableToLoadEvents: '',
		loading: '',
		loadingEvents: '',
		eventsExplorerTitle: '',
		editorMode: '',
		formatLabel: '',
		languageLabel: '',
		languageAuto: '',
		eventsLabel: '',
		syncLanguage: {
			title: '',
			message: '',
			dontAskAgain: '',
		},
		help: '',
		editorSettings: '',
		openVSCodeSettings: '',
		openOnlineEditor: '',
		oldEditor: '',
		originalEditor: '',
		basicTutorial: '',
		tutorialSection: '',
		discussionSection: '',
		sampleDownload: '',
		mute: '',
		unmute: '',
	},
	common: {
		info: '',
		yes: '',
		no: '',
		confirm: '',
		cancel: '',
		back: '',
		close: '',
		save: '',
		add: '',
		edit: '',
		remove: '',
		apply: '',
		openHelper: '',
		other: '',
		details: '',
		undo: '',
		redo: '',
		duplicate: '',
		copy: '',
		cut: '',
		moreActions: '',
	},
	editor: {
		visualEditor: '',
		jsonEditor: '',
		editAsJson: '',
		backToVisual: '',
	},
	settings: {
		baseSettingsTitle: '',
		otherSettingsTitle: '',
		configsTitle: '',
		configSection: '',
		viewConfigs: '',
		stage: '',
		preload: '',
		resources: '',
		sources: '',
		configs: '',
		stageSize: '',
		background: '',
		resolution: '',
		alignment: '',
		position: '',
		width: '',
		height: '',
		color: '',
		resourcesExcludePlaceholder: '',
		sourcesPlaceholder: '',
		resolutionModes: {
			showAll: '',
			exactFit: '',
			noBorder: '',
			fixedWidth: '',
			fixedHeight: '',
			origin: '',
		},
		align: {
			left: '',
			center: '',
			right: '',
			top: '',
			middle: '',
			bottom: '',
		},
	},
	events: {
		eventActions: '',
		addEvent: '',
		folder: '',
		allFolders: '',
		noFolder: '',
		noDescription: '',
		editEvent: '',
		expandEvent: '',
		collapseEvent: '',
		eventName: '',
		eventNameExists: '',
		eventNameRequired: '',
		eventNameInvalid: '',
		renameEventNameHint: '',
		renameFolderHint: '',
		folderNameInvalid: '',
		status: {
			active: '',
			disabled: '',
		},
		schedule: {
			start: '',
			checkInterval: '',
			repeats: '',
			repeatInterval: '',
		},
		flags: {
			devOnly: '',
			referenceOnly: '',
		},
		chips: {
			start: '',
			check: '',
			repeat: '',
			interval: '',
			dev: '',
			triple: '',
		},
		sorting: {
			title: '',
			editPreset: '',
			enableSort: '',
			disableSort: '',
			savePreset: '',
			loadPreset: '',
			defaultPreset: '',
			presetName: '',
			presetNamePlaceholder: '',
			existingPresets: '',
			noPresets: '',
			confirmOverwrite: '',
			selectPreset: '',
			deletePreset: '',
			confirmDelete: '',
		},
	},
	logic: {
		actionsLabel: '',
		blocks: {
			trigger: '',
			check: '',
			action: '',
		},
		empty: {
			trigger: '',
			check: '',
			action: '',
		},
		add: {
			trigger: '',
			check: '',
			action: '',
		},
		elseTrigger: '',
		unknownType: '',
		addAboveType: '',
		addBelowType: '',
		toggleSectionBlock: '',
		toggleAllType: '',
		expandTypeList: '',
		collapseTypeList: '',
	},
	list: {
		arrayItemActions: '',
		collapse: '',
		collapseAll: '',
		expand: '',
		expandAll: '',
		selectAll: '',
		cancelSelectAll: '',
		selectAllList: '',
		addItem: '',
		move: '',
		moveUp: '',
		moveDown: '',
		moveLeft: '',
		moveRight: '',
		moveToTop: '',
		moveToBottom: '',
		moveToEvent: '',
		moveSelectionHere: '',
		copyList: '',
		cutList: '',
		pasteHere: '',
		pastePrompt: '',
		removeList: '',
		removeAll: '',
	},
	state: {
		enable: '',
		disable: '',
		enableDisable: '',
		enableList: '',
		disableList: '',
		enableDisableList: '',
		booleanTrue: '',
		booleanFalse: '',
	},
	validation: {
		invalidJson: '',
		numberFormatError: '',
		noItems: '',
		noMatches: '',
		missingDefinition: '',
		noSchemaProperties: '',
	},
	navigation: {
		root: '',
		search: '',
		searchResults: '',
		goBackTo: '',
		goForwardTo: '',
		goUpTo: '',
	},
};

export const translation = generateTranslation(json, '');

export type TranslationJson = ILanguageJson<typeof json>;
