import { getTranslation, LANG } from '@shared';
import { TranslationJson } from './Trans';

const json: TranslationJson = {
	app: {
		unableToLoadEvents: '無法載入事件',
		loading: '載入中',
		loadingEvents: '正在載入事件...',
		eventsExplorerTitle: '事件總覽',
		editorMode: '編輯模式',
		formatLabel: '格式',
		languageLabel: '語言',
		languageAuto: '同 VS Code',
		eventsLabel: '事件',
		syncLanguage: {
			title: '同步語言設定',
			message: '你想將語言設定同步到 VS Code 設定嗎？',
			dontAskAgain: '不要再詢問我',
		},
		help: '幫助',
		editorSettings: '編輯器設定',
		openVSCodeSettings: '開啟 VS Code 設定',
		openOnlineEditor: '開啟線上編輯器',
		oldEditor: '舊編輯器',
		originalEditor: '原編輯器',
		basicTutorial: '基礎教學',
		tutorialSection: '教學區',
		discussionSection: '討論區',
		sampleDownload: '範例檔下載',
		mute: '靜音',
		unmute: '取消靜音',
	},
	common: {
		info: '資訊',
		yes: '是',
		no: '否',
		confirm: '確認',
		cancel: '取消',
		back: '返回',
		close: '關閉',
		save: '儲存',
		add: '新增',
		edit: '編輯',
		remove: '移除',
		apply: '套用',
		openHelper: '編輯小幫手',
		other: '其他',
		details: '詳細',
		undo: '復原',
		redo: '重做',
		duplicate: '建立副本',
		copy: '複製',
		cut: '剪下',
		moreActions: '更多選項',
	},
	editor: {
		visualEditor: '視覺編輯器',
		jsonEditor: 'JSON 編輯器',
		editAsJson: '以 JSON 編輯',
		backToVisual: '返回視覺編輯器',
	},
	settings: {
		baseSettingsTitle: '基本設定',
		otherSettingsTitle: '其餘設定',
		configsTitle: '設定',
		configSection: '設定',
		viewConfigs: '檢視設定',
		stage: '舞台',
		preload: '預載入',
		resources: '資源',
		sources: '原始碼',
		configs: '設定',
		stageSize: '舞台尺寸',
		background: '背景顏色',
		resolution: '解析度',
		alignment: '對齊',
		position: '位置',
		width: '寬度',
		height: '高度',
		color: '顏色',
		resourcesExcludePlaceholder: '以逗號分隔',
		sourcesPlaceholder: '以逗號分隔',
		resolutionModes: {
			showAll: '縮放至舞台大小(長寬比不變)',
			exactFit: '縮放至視窗大小(變動長寬比)',
			noBorder: '填滿舞台大小(長寬比不變)',
			fixedWidth: '縮放至舞台寬度(長寬比不變)',
			fixedHeight: '縮放至舞台高度(長寬比不變)',
			origin: '保持原尺寸',
		},
		align: {
			left: '靠左',
			center: '置中',
			right: '靠右',
			top: '置頂',
			middle: '置中',
			bottom: '置底',
		},
	},
	events: {
		eventActions: '事件操作',
		addEvent: '新增事件',
		folder: '資料夾',
		allFolders: '全部資料夾',
		noFolder: '沒有資料夾',
		noDescription: '沒有描述',
		editEvent: '編輯事件',
		expandEvent: '展開事件',
		collapseEvent: '收合事件',
		eventName: '事件名稱',
		eventNameExists: '事件名稱已存在',
		eventNameRequired: '事件名稱不可空白',
		eventNameInvalid: '事件名稱必須為 1-60 個字元，且不能包含 .,/\\*<>{} 或空白字元。',
		renameEventNameHint: '雙擊以重新命名事件',
		renameFolderHint: '雙擊以重新命名資料夾',
		folderNameInvalid: '資料夾名稱不可包含 < > { } 字元。',
		status: {
			active: '已啟用',
			disabled: '已停用',
		},
		schedule: {
			start: '開始',
			checkInterval: '檢查間隔',
			repeats: '重複次數',
			repeatInterval: '重複間隔',
		},
		flags: {
			devOnly: '僅限開發',
			referenceOnly: '僅供參考',
		},
		chips: {
			start: '開始',
			check: '檢查',
			repeat: '重複',
			interval: '間隔',
			dev: '開發',
			triple: '觸發/檢查/動作',
		},
		sorting: {
			title: '排序',
			editPreset: '編輯預設',
			enableSort: '啟用排序',
			disableSort: '停用排序',
			savePreset: '儲存預設',
			loadPreset: '讀取預設',
			defaultPreset: '預設排序',
			presetName: '預設名稱',
			presetNamePlaceholder: '輸入預設名稱',
			existingPresets: '現有預設',
			noPresets: '沒有已儲存的預設',
			confirmOverwrite: '預設「{{name}}」已存在，是否覆蓋？',
			selectPreset: '選擇預設',
			deletePreset: '刪除預設',
			confirmDelete: '確定要刪除預設「{{name}}」嗎？',
		},
	},
	logic: {
		actionsLabel: '邏輯操作',
		blocks: {
			trigger: '觸發',
			check: '檢查',
			action: '動作',
		},
		empty: {
			trigger: '沒有觸發',
			check: '沒有檢查',
			action: '沒有動作',
		},
		add: {
			trigger: '新增觸發',
			check: '新增檢查',
			action: '新增動作',
		},
		elseTrigger: '否則觸發',
		unknownType: '未知型別',
		addAboveType: '在上方新增{type}',
		addBelowType: '在下方新增{type}',
		toggleSectionBlock: '收合/展開{type}區塊',
		toggleAllType: '收合/展開所有{type}',
		expandTypeList: '展開列表',
		collapseTypeList: '收合列表',
	},
	list: {
		arrayItemActions: '陣列項目操作',
		collapse: '收合',
		collapseAll: '全部收合',
		expand: '展開',
		expandAll: '全部展開',
		selectAll: '全選',
		cancelSelectAll: '取消全選',
		selectAllList: '全選列表',
		addItem: '新增項目',
		move: '移動',
		moveUp: '上移',
		moveDown: '下移',
		moveLeft: '左移',
		moveRight: '右移',
		moveToTop: '移至頂部',
		moveToBottom: '移至底部',
		moveToEvent: '移至事件',
		moveSelectionHere: '將選取移到這裡',
		copyList: '複製列表',
		cutList: '剪下列表',
		pasteHere: '貼上',
		pastePrompt: '貼上邏輯 JSON',
		removeList: '移除列表',
		removeAll: '全部刪除',
	},
	state: {
		enable: '啟用',
		disable: '停用',
		enableDisable: '啟用/停用',
		enableList: '啟用列表',
		disableList: '停用列表',
		enableDisableList: '啟用/停用列表',
		booleanTrue: '是',
		booleanFalse: '否',
	},
	validation: {
		invalidJson: '無效的 JSON',
		numberFormatError: '填入的值必須符合型別 number.',
		noItems: '沒有項目',
		noMatches: '沒有符合的結果',
		missingDefinition: '缺少定義',
		noSchemaProperties: '此設定未定義任何屬性。',
	},
	navigation: {
		root: '根目錄',
		search: '搜尋',
		searchResults: '搜尋結果',
		goBackTo: '返回 {{name}}',
		goForwardTo: '前往 {{name}}',
		goUpTo: '回到 {{name}}',
	},
};

getTranslation(LANG.ZH).importJson(json);
